# Generated by Django 4.2.6 on 2023-11-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('commentary', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=0, max_digits=2)),
                ('minutes', models.DecimalField(decimal_places=0, max_digits=1)),
                ('expense', models.DecimalField(decimal_places=2, max_digits=7)),
                ('commentary', models.CharField(max_length=60)),
            ],
        ),
    ]
