# Generated by Django 4.2.6 on 2023-11-13 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timeentry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='expense',
            new_name='claim_expense',
        ),
        migrations.RemoveField(
            model_name='record',
            name='date',
        ),
        migrations.RemoveField(
            model_name='record',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='record',
            name='minutes',
        ),
        migrations.AddField(
            model_name='record',
            name='case',
            field=models.CharField(default='CASE001', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='claim_hours',
            field=models.DecimalField(decimal_places=2, default='1.00', max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='datetime_approved',
            field=models.DateTimeField(default='2006-10-25 14:30:59'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='datetime_input',
            field=models.DateTimeField(default='2006-10-25 14:30:59'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='datetime_paid',
            field=models.DateTimeField(default='2006-10-25 14:30:59'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='datetime_submitted',
            field=models.DateTimeField(default='2006-10-25 14:30:59'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open Time Entry.  Not yet submitted'), ('SUBMITTED', 'Submitted Time Entry.  Waiting for approval'), ('APPROVED', 'Approved Time Entry. Waiting for payment'), ('PAID', 'Paid Time Entry. No further action required')], default='OPEN', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='user',
            field=models.ForeignKey(default='123', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='username',
            field=models.CharField(default='KMURRAY24', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='record',
            name='type',
            field=models.CharField(choices=[('TIME', 'Time Entry'), ('EXPENSE', 'Expense Entry.')], max_length=7),
        ),
    ]
