# Generated by Django 4.2.6 on 2023-11-15 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeentry', '0002_rename_expense_record_claim_expense_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='user',
        ),
        migrations.RemoveField(
            model_name='record',
            name='username',
        ),
    ]
