# Generated by Django 4.2.6 on 2023-11-21 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeentry', '0003_remove_record_user_remove_record_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('TIME', 'Time Entry'), ('EXPENSE', 'Expense Entry.')], max_length=7)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('expense', models.DecimalField(decimal_places=2, max_digits=7)),
                ('notes', models.CharField(max_length=60)),
                ('datetime_input', models.DateTimeField(blank=True, null=True)),
                ('datetime_submitted', models.DateTimeField(blank=True, null=True)),
                ('datetime_approved', models.DateTimeField(blank=True, null=True)),
                ('datetime_paid', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open Time Entry.  Not yet submitted'), ('SUBMITTED', 'Submitted Time Entry.  Waiting for approval'), ('APPROVED', 'Approved Time Entry. Waiting for payment'), ('PAID', 'Paid Time Entry. No further action required')], max_length=10)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeentry.case')),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=60, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=60, verbose_name='Email')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.RenameField(
            model_name='period',
            old_name='commentary',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='claim',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeentry.expert'),
        ),
        migrations.AddField(
            model_name='claim',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeentry.period'),
        ),
    ]
