# Generated by Django 4.2.6 on 2023-11-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeentry', '0004_case_claim_expert_delete_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
