# Generated by Django 4.2.6 on 2023-11-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeentry', '0005_alter_case_id_alter_claim_id_alter_expert_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='begin_date',
            field=models.DateField(verbose_name='Begin Date'),
        ),
        migrations.AlterField(
            model_name='period',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
    ]
