# Generated by Django 4.2.6 on 2023-11-22 22:52

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('timeentry', '0008_rename_first_name_expert_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
