# Generated by Django 4.2.6 on 2023-11-23 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeentry', '0009_expert_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='period',
            old_name='begin_date',
            new_name='begindate',
        ),
        migrations.RenameField(
            model_name='period',
            old_name='end_date',
            new_name='enddate',
        ),
    ]
