# Generated by Django 4.2.6 on 2023-11-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeentry', '0010_rename_begin_date_period_begindate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='firstname',
            field=models.CharField(max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='lastname',
            field=models.CharField(max_length=30, verbose_name='Last Name'),
        ),
    ]
