# Generated by Django 4.2.6 on 2023-11-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeentry', '0011_alter_case_name_alter_expert_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='period',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
