# Generated by Django 4.2.6 on 2023-11-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeentry', '0012_alter_claim_notes_alter_period_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='date',
            field=models.DateField(default='2022-01-01', verbose_name='Date'),
            preserve_default=False,
        ),
    ]
