# Generated by Django 4.2.6 on 2023-11-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeentry', '0013_claim_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True, verbose_name='Email'),
        ),
    ]
