# Generated by Django 4.2.6 on 2023-11-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeentry', '0014_alter_expert_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
