# Generated by Django 4.2.6 on 2023-11-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeentry', '0015_alter_claim_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='expense',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='claim',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
